/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class FrameEditarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameEditarCliente
     */
    public FrameEditarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelGeneral = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtci = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JComboBox<>();
        nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelBotones = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.CardLayout());

        panelGeneral.setLayout(new javax.swing.BoxLayout(panelGeneral, javax.swing.BoxLayout.Y_AXIS));

        panelDatos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        panelDatos.add(jLabel1, gridBagConstraints);

        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 58);
        panelDatos.add(txtnombres, gridBagConstraints);

        jLabel2.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        panelDatos.add(jLabel2, gridBagConstraints);

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 58);
        panelDatos.add(txtapellidos, gridBagConstraints);

        jLabel3.setText("Cédula o Pasaporte:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        panelDatos.add(jLabel3, gridBagConstraints);

        txtci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 58);
        panelDatos.add(txtci, gridBagConstraints);

        jLabel4.setText("Fecha Nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 52, 0, 0);
        panelDatos.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Nacionalidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        panelDatos.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Número Telefónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 52, 26, 0);
        panelDatos.add(jLabel6, gridBagConstraints);

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 192;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 46, 0, 58);
        panelDatos.add(txttelefono, gridBagConstraints);

        jLabel7.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 52, 0, 0);
        panelDatos.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Codigo Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 52, 0, 0);
        panelDatos.add(jLabel8, gridBagConstraints);

        nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UN PAIS" }));
        nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 58);
        panelDatos.add(nacionalidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 46, 0, 58);
        panelDatos.add(nacimiento, gridBagConstraints);

        jLabel9.setText("usuariooooo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 45, 0, 58);
        panelDatos.add(jLabel9, gridBagConstraints);

        jLabel10.setText("algo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 179;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 58);
        panelDatos.add(jLabel10, gridBagConstraints);

        panelGeneral.add(panelDatos);
        panelGeneral.add(jSeparator1);

        btnregistrar.setText("Guardar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnregistrar);

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(btnlimpiar);

        panelGeneral.add(panelBotones);

        getContentPane().add(panelGeneral, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
//        txtnombres.setBackground(Color.white);
//        char c;
//        letrasNumeros(c = evt.getKeyChar(), evt, 1);
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
//        txtapellidos.setBackground(Color.white);
//        char c;
//        letrasNumeros(c = evt.getKeyChar(), evt, 1);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciKeyTyped
//        txtci.setBackground(Color.white);
    }//GEN-LAST:event_txtciKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
////        txttelefono.setBackground(Color.white);
////        char c;
////        letrasNumeros(c = evt.getKeyChar(), evt, 2);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadActionPerformed
//        if (nacionalidad.getSelectedIndex() == 0) {
//            ciudadania = null;
//        } else {
//            ciudadania = nacionalidad.getSelectedItem().toString();
//        }
    }//GEN-LAST:event_nacionalidadActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtnombres.setText(null);
        txtapellidos.setText(null);
        txtci.setText(null);
               txttelefono.setText(null);
        nacionalidad.setSelectedIndex(0);
        nacimiento.setDate(null);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
//        String nombres = txtnombres.getText();
//        String apellidos = txtapellidos.getText();
//        String id = txtci.getText();
//        Date fechaNacimiento;
//        fechaNacimiento = fechaNacimiento();
//        int codigo;
//
//        String telefono = txttelefono.getText();
//        String usuario = txtusuario.getText();
//        clave1 = txtclave1.getText();
//        clave2 = txtclave2.getText();
//
//        List<String> campos = new ArrayList<>();
//        campos.add(nombres);
//        campos.add(apellidos);
//        campos.add(id);
//        campos.add(telefono);
//        campos.add(usuario);
//        campos.add(clave1);
//        campos.add(clave2);
//
//        List<Integer> camposVacios = validar.camposVacios(campos);
//        if (!camposVacios.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Campos obligatorios vacios"); //mensaje
//
//            for (Integer camposVacio : camposVacios) {  //devuelve la psocion de la lista de campos vacios leyendo la lista
//
//                switch (camposVacio) {
//                    case 0:
//                    txtnombres.setBackground(Color.red);
//                    break;
//                    case 1:
//                    txtapellidos.setBackground(Color.red);
//                    break;
//                    case 2:
//                    txtci.setBackground(Color.red);
//                    break;
//                    case 3:
//                    txttelefono.setBackground(Color.red);
//                    break;
//                    case 4:
//                    txtusuario.setBackground(Color.red);
//                    break;
//                    case 5:
//                    txtclave1.setBackground(Color.red);
//                    break;
//                    case 6:
//                    txtclave2.setBackground(Color.red);
//                    lblconfirmacion.setForeground(Color.red);
//                    lblconfirmacion.setText("Contraseña incorrecta");
//                    break;
//
//                }
//            }
//        } else if ((validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)).equals(validar.encriptaEnMD5(validar.encriptaEnMD5(clave2)))) && fechaNacimiento != null && ciudadania != null) {
//            lblconfirmacion.setForeground(Color.green);
//            lblconfirmacion.setText("Contraseña correcta");
//            if (btncliente.isSelected()) {
//                cliente = new Cliente(usuario, validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)), nombres, apellidos, ciudadania, id, fechaNacimiento, telefono);
//                conexion.obtener();
//                new Tabla(conexion).agregarValores((Object) cliente, 1);
//                Ingreso ingreso = new Ingreso();
//                ingreso.setVisible(true);
//                dispose();
//            } else {
//                empleado = new Empleado(usuario, validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)), nombres, apellidos, ciudadania, id, fechaNacimiento, telefono);
//                conexion.obtener();
//                new Tabla(conexion).agregarValores((Object) empleado, 4);
//                Ingreso ingreso = new Ingreso();
//                ingreso.setVisible(true);
//
//            }
//
//        } else if (!(validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)).equals(validar.encriptaEnMD5(validar.encriptaEnMD5(clave2))))) {
//            lblconfirmacion.setForeground(Color.red);
//            lblconfirmacion.setText("Contraseña incorrecta");
//
//        } else if (fechaNacimiento == null) {
//            JOptionPane.showMessageDialog(null, "Fecha de nacimiento incorecta");
//
//        } else if (ciudadania == null) {
//            JOptionPane.showMessageDialog(null, "Nacionalidad incorrecta");
//        }

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JComboBox<String> nacionalidad;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtci;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
