/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.SimpleDateFormat;
import java.util.Date;

public class FrameEstadia extends javax.swing.JInternalFrame {

//    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM");
//    private SimpleDateFormat sdf2 = new SimpleDateFormat("YYYY");
    private Date fechaMin = new Date();
    private int contador = 0;

    public FrameEstadia() {
        initComponents();
        this.setTitle("Seleccione dias para su estadia");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelFechas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbluno = new javax.swing.JLabel();
        dateLLegada = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        dateSalida = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        lbldos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblconfirmacion = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(438, 493));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelFechas.setPreferredSize(new java.awt.Dimension(438, 493));
        panelFechas.setLayout(new javax.swing.BoxLayout(panelFechas, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(30, 200));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(308, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DIA DE LLEGADA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        lbluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluno.setText("ASFASFDS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 247;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 10, 0, 0);
        jPanel1.add(lbluno, gridBagConstraints);

        dateLLegada.setMinSelectableDate(new Date());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 261;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanel1.add(dateLLegada, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(308, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        dateSalida.setDateFormatString("d/MM/YYYY");
        dateSalida.setDoubleBuffered(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 271;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanel2.add(dateSalida, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIA DE SALIDA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 225;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 10, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        lbldos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldos.setText("ASFASFDS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 247;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 0);
        jPanel2.add(lbldos, gridBagConstraints);

        jPanel4.add(jPanel2);

        panelFechas.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(620, 20));
        jPanel5.setLayout(new java.awt.CardLayout());

        lblconfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblconfirmacion.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel5.add(lblconfirmacion, "card2");

        panelFechas.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(620, 40));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButton2.setText("Verificar");
        jButton2.setMaximumSize(new java.awt.Dimension(3, 3));
        jButton2.setPreferredSize(new java.awt.Dimension(73, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton1.setText("Avanzar");
        jButton1.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel6.add(jButton1);

        panelFechas.add(jPanel6);

        getContentPane().add(panelFechas, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (dateLLegada.getDate().before(dateSalida.getDate())) {
            System.out.println("HOLA");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

//   private Date minimo() {
//                revalidate();
//                Date dateMin = new Date();
//                dateMin = dateLLegada.getDate();
//                return dateMin;
//            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateLLegada;
    private com.toedter.calendar.JDateChooser dateSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblconfirmacion;
    private javax.swing.JLabel lbldos;
    private javax.swing.JLabel lbluno;
    private javax.swing.JPanel panelFechas;
    // End of variables declaration//GEN-END:variables
}
