/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JRadioButton;

/**
 *
 * @author Toshiba
 */
public class FrameAlimentacion extends javax.swing.JInternalFrame {

    private int contador_radiobutton = 0;
    private JRadioButton boton = new JRadioButton();

    public FrameAlimentacion() {
        initComponents();
        this.setTitle("ALIMENTACION");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbtdesayuno = new javax.swing.JRadioButton();
        rbtmerienda = new javax.swing.JRadioButton();
        rbtalmuerzo = new javax.swing.JRadioButton();
        rbtcompleto = new javax.swing.JRadioButton();
        rbtninguno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        precioAlmuerzo = new javax.swing.JLabel();
        precioDesayuno = new javax.swing.JLabel();
        precioMerienda = new javax.swing.JLabel();
        precioCompleto = new javax.swing.JLabel();
        precioNinguno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(438, 493));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 322));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        rbtdesayuno.setText("Desayuno");
        rbtdesayuno.setName("desayuno"); // NOI18N
        rbtdesayuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtdesayunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 41, 0, 29);
        jPanel1.add(rbtdesayuno, gridBagConstraints);

        rbtmerienda.setText("Merienda");
        rbtmerienda.setName("merienda"); // NOI18N
        rbtmerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtmeriendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtmerienda, gridBagConstraints);

        rbtalmuerzo.setText("Almuerzo");
        rbtalmuerzo.setName("almerzo"); // NOI18N
        rbtalmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtalmuerzoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtalmuerzo, gridBagConstraints);

        rbtcompleto.setText("Completo");
        rbtcompleto.setName("completo"); // NOI18N
        rbtcompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcompletoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtcompleto, gridBagConstraints);

        rbtninguno.setText("Ninguno");
        rbtninguno.setName("ninguno"); // NOI18N
        rbtninguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtningunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 58, 29);
        jPanel1.add(rbtninguno, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        precioAlmuerzo.setText("+ $ 8,00");
        precioAlmuerzo.setName("8.00"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 58);
        jPanel3.add(precioAlmuerzo, gridBagConstraints);

        precioDesayuno.setText("+ $ 5,00");
        precioDesayuno.setName("5.00"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 65, 0, 58);
        jPanel3.add(precioDesayuno, gridBagConstraints);

        precioMerienda.setText("+ $ 8,00");
        precioMerienda.setName("8.00"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 58);
        jPanel3.add(precioMerienda, gridBagConstraints);

        precioCompleto.setText("+ $ 17,00");
        precioCompleto.setName("17.00"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 58);
        jPanel3.add(precioCompleto, gridBagConstraints);

        precioNinguno.setText("+ $ 0,00");
        precioNinguno.setName("0.00"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 62, 58);
        jPanel3.add(precioNinguno, gridBagConstraints);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtdesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtdesayunoActionPerformed
        radioButton(1, rbtdesayuno);
    }//GEN-LAST:event_rbtdesayunoActionPerformed

    private void rbtmeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtmeriendaActionPerformed
        radioButton(1, rbtmerienda);
    }//GEN-LAST:event_rbtmeriendaActionPerformed

    private void rbtalmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtalmuerzoActionPerformed
        radioButton(1, rbtalmuerzo);
    }//GEN-LAST:event_rbtalmuerzoActionPerformed

    private void rbtcompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcompletoActionPerformed
        radioButton(2, rbtcompleto);
    }//GEN-LAST:event_rbtcompletoActionPerformed

    private void rbtningunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtningunoActionPerformed
        radioButton(3, rbtninguno);
    }//GEN-LAST:event_rbtningunoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        System.out.println(boton.getText());
    }//GEN-LAST:event_aceptarActionPerformed

    private void radioButton(int contador, JRadioButton btn) {
        boton = btn;
        switch (contador) {

            case 1:
                if (rbtalmuerzo.isSelected() && rbtmerienda.isSelected() && rbtdesayuno.isSelected()) {
                    rbtalmuerzo.setSelected(false);
                    rbtmerienda.setSelected(false);
                    rbtdesayuno.setSelected(false);
                    rbtcompleto.setSelected(true);
                } else {
                    rbtcompleto.setSelected(false);
                    rbtninguno.setSelected(false);
                }
                break;

            case 2:
                rbtninguno.setSelected(false);
                rbtalmuerzo.setSelected(false);
                rbtmerienda.setSelected(false);
                rbtdesayuno.setSelected(false);
                break;

            case 3:
                rbtalmuerzo.setSelected(false);
                rbtmerienda.setSelected(false);
                rbtdesayuno.setSelected(false);
                rbtcompleto.setSelected(false);
                break;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel precioAlmuerzo;
    private javax.swing.JLabel precioCompleto;
    private javax.swing.JLabel precioDesayuno;
    private javax.swing.JLabel precioMerienda;
    private javax.swing.JLabel precioNinguno;
    private javax.swing.JRadioButton rbtalmuerzo;
    private javax.swing.JRadioButton rbtcompleto;
    private javax.swing.JRadioButton rbtdesayuno;
    private javax.swing.JRadioButton rbtmerienda;
    private javax.swing.JRadioButton rbtninguno;
    // End of variables declaration//GEN-END:variables
}
