/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class FrameAlimentacion extends javax.swing.JInternalFrame {

    private int contador_radiobutton = 0;

    public FrameAlimentacion() {
        initComponents();
        this.setTitle("ALIMENTACION");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbtdesayuno = new javax.swing.JRadioButton();
        rbtmerienda = new javax.swing.JRadioButton();
        rbtalmuerzo = new javax.swing.JRadioButton();
        rbtcompleto = new javax.swing.JRadioButton();
        rbtninguno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(438, 493));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 322));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        rbtdesayuno.setText("Desayuno");
        rbtdesayuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtdesayunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 41, 0, 29);
        jPanel1.add(rbtdesayuno, gridBagConstraints);

        rbtmerienda.setText("Merienda");
        rbtmerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtmeriendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtmerienda, gridBagConstraints);

        rbtalmuerzo.setText("Almuerzo");
        rbtalmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtalmuerzoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtalmuerzo, gridBagConstraints);

        rbtcompleto.setText("Completo");
        rbtcompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcompletoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 29);
        jPanel1.add(rbtcompleto, gridBagConstraints);

        rbtninguno.setText("Ninguno");
        rbtninguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtningunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 58, 29);
        jPanel1.add(rbtninguno, gridBagConstraints);

        jPanel4.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("+ $ 8,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 58);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel4.setText("+ $ 5,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 65, 0, 58);
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel7.setText("+ $ 8,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 58);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("+ $ 17,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 58);
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setText("+ $ 0,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 62, 58);
        jPanel3.add(jLabel9, gridBagConstraints);

        jPanel4.add(jPanel3);

        getContentPane().add(jPanel4);

        jButton2.setText("Aceptar");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtdesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtdesayunoActionPerformed
        radioButton(1);
    }//GEN-LAST:event_rbtdesayunoActionPerformed

    private void rbtmeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtmeriendaActionPerformed
        radioButton(1);
    }//GEN-LAST:event_rbtmeriendaActionPerformed

    private void rbtalmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtalmuerzoActionPerformed
        radioButton(1);
    }//GEN-LAST:event_rbtalmuerzoActionPerformed

    private void rbtcompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcompletoActionPerformed
        radioButton(2);
    }//GEN-LAST:event_rbtcompletoActionPerformed

    private void rbtningunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtningunoActionPerformed
        radioButton(3);
    }//GEN-LAST:event_rbtningunoActionPerformed

    private void radioButton(int contador) {
        switch (contador) {

            case 1:
                if (rbtalmuerzo.isSelected() && rbtmerienda.isSelected() && rbtdesayuno.isSelected()) {
                    rbtalmuerzo.setSelected(false);
                    rbtmerienda.setSelected(false);
                    rbtdesayuno.setSelected(false);
                    rbtcompleto.setSelected(true);
                } else {
                    rbtcompleto.setSelected(false);
                    rbtninguno.setSelected(false);
                }
                break;

            case 2:
                rbtninguno.setSelected(false);
                rbtalmuerzo.setSelected(false);
                rbtmerienda.setSelected(false);
                rbtdesayuno.setSelected(false);
                break;

            case 3:
                rbtalmuerzo.setSelected(false);
                rbtmerienda.setSelected(false);
                rbtdesayuno.setSelected(false);
                rbtcompleto.setSelected(false);
                break;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbtalmuerzo;
    private javax.swing.JRadioButton rbtcompleto;
    private javax.swing.JRadioButton rbtdesayuno;
    private javax.swing.JRadioButton rbtmerienda;
    private javax.swing.JRadioButton rbtninguno;
    // End of variables declaration//GEN-END:variables
}
