/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class Gestion extends javax.swing.JFrame {

    private boolean tipo;

    private FrameEditarHabitacion editarHabitacion = new FrameEditarHabitacion();
    private FrameEditarCliente editarcliente = new FrameEditarCliente();
    private FrameRevisar revisarcliente = new FrameRevisar();

    public Gestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNombre = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbxBusqueda = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelGeneral = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuRevHabitacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuEditCliente = new javax.swing.JMenuItem();
        menuRevCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNombreMouseClicked(evt);
            }
        });

        lblNombre.setText("kike");
        panelNombre.add(lblNombre);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        panelNombre.add(jLabel1);

        lblUsuario.setText("COD. USUARIO");
        panelNombre.add(lblUsuario);

        getContentPane().add(panelNombre);

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 45));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        cbxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por:", "Cedula", "Usuario", "CodigoUsuario" }));
        cbxBusqueda.setToolTipText("");
        cbxBusqueda.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 53, 0, 0);
        jPanel2.add(cbxBusqueda, gridBagConstraints);

        txtBusqueda.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 0);
        jPanel2.add(txtBusqueda, gridBagConstraints);

        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 29, 3, 27);
        jPanel2.add(btnBuscar, gridBagConstraints);

        getContentPane().add(jPanel2);

        panelGeneral.setPreferredSize(new java.awt.Dimension(634, 440));
        panelGeneral.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelGeneral);

        jMenu3.setText("Habitacion");

        menuRevHabitacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRevHabitacion.setText("Editar");
        menuRevHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRevHabitacionActionPerformed(evt);
            }
        });
        jMenu3.add(menuRevHabitacion);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Cliente");

        menuEditCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuEditCliente.setText("Editar");
        menuEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditClienteActionPerformed(evt);
            }
        });
        jMenu4.add(menuEditCliente);

        menuRevCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuRevCliente.setText("Revisar");
        menuRevCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRevClienteActionPerformed(evt);
            }
        });
        jMenu4.add(menuRevCliente);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditClienteActionPerformed
        habilitar();
        tipo = true;
        panelGeneral.removeAll();

    }//GEN-LAST:event_menuEditClienteActionPerformed

    private void menuRevClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRevClienteActionPerformed
        habilitar();
        tipo = false;
        panelGeneral.removeAll();

    }//GEN-LAST:event_menuRevClienteActionPerformed

    private void panelNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNombreMouseClicked
        if (JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA ERRAR SESION?") == 0) {

            this.setVisible(false);
            new Ingreso().setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_panelNombreMouseClicked

    private void menuRevHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRevHabitacionActionPerformed
        cambioFrame(revisarcliente);

    }//GEN-LAST:event_menuRevHabitacionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (tipo) {
            cambioFrame(editarcliente);
        } else {
            cambioFrame(revisarcliente);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cambioFrame(JInternalFrame frame) {

        panelGeneral.removeAll();
        panelGeneral.add(frame);

    }

    private void habilitar() {

        cbxBusqueda.setEnabled(true);
        txtBusqueda.setEnabled(true);
        btnBuscar.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuEditCliente;
    private javax.swing.JMenuItem menuRevCliente;
    private javax.swing.JMenuItem menuRevHabitacion;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
