package vista;

import controlador.Conexion;

import controlador.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import modelo.*;

public class Registros extends javax.swing.JFrame {
    
    private Date date = new Date();
    
    private Conexion conexion = new Conexion();
    private controlador.Validacion validar = new controlador.Validacion();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
    private final String CONFIRMACION = validar.encriptaEnMD5(validar.encriptaEnMD5("12345"));
    private String clave1, clave2;
    public Cliente cliente;
    public Empleado empleado;
    private String ciudadania;
    private Date date2 = new Date();
    
    public Registros() {
        initComponents();
        setLocationRelativeTo(null);
        nacionalidad.setModel(nacionalidad());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelGeneral = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtci = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtclave1 = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        txtclave2 = new javax.swing.JPasswordField();
        nacionalidad = new javax.swing.JComboBox<>();
        lblconfirmacion = new javax.swing.JLabel();
        nacimiento = new com.toedter.calendar.JDateChooser();
        panelBotones = new javax.swing.JPanel();
        btnvolver = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelGeneral.setLayout(new java.awt.GridBagLayout());

        panelDatos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel1, gridBagConstraints);

        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtnombres, gridBagConstraints);

        jLabel2.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel2, gridBagConstraints);

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtapellidos, gridBagConstraints);

        jLabel3.setText("Cédula o Pasaporte:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel3, gridBagConstraints);

        txtci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtci, gridBagConstraints);

        jLabel4.setText("Fecha Nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 32, 0, 0);
        panelDatos.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Nacionalidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Número Telefónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 32, 0, 0);
        panelDatos.add(jLabel6, gridBagConstraints);

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 0, 10);
        panelDatos.add(txttelefono, gridBagConstraints);

        jLabel7.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 32, 0, 0);
        panelDatos.add(jLabel7, gridBagConstraints);

        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtusuario, gridBagConstraints);

        jLabel8.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel8, gridBagConstraints);

        txtclave1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclave1KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtclave1, gridBagConstraints);

        jProgressBar1.setForeground(new java.awt.Color(10, 200, 100));
        jProgressBar1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 35, 0, 10);
        panelDatos.add(jProgressBar1, gridBagConstraints);

        jLabel9.setText("Validacion contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        panelDatos.add(jLabel9, gridBagConstraints);

        txtclave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclave2KeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(txtclave2, gridBagConstraints);

        nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UN PAIS" }));
        nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 35, 0, 10);
        panelDatos.add(nacionalidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.ipadx = 232;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 0, 10);
        panelDatos.add(lblconfirmacion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 35, 0, 10);
        panelDatos.add(nacimiento, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelGeneral.add(panelDatos, gridBagConstraints);

        panelBotones.setLayout(new java.awt.GridBagLayout());

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 0, 67);
        panelBotones.add(btnvolver, gridBagConstraints);

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 29, 0, 0);
        panelBotones.add(btnlimpiar, gridBagConstraints);

        btnregistrar.setText("Registrarme");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 93, 0, 0);
        panelBotones.add(btnregistrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        panelGeneral.add(panelBotones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 501;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        panelGeneral.add(jSeparator1, gridBagConstraints);

        getContentPane().add(panelGeneral, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadActionPerformed
        if (nacionalidad.getSelectedIndex() == 0) {
            ciudadania = null;
        } else {
            ciudadania = nacionalidad.getSelectedItem().toString();
        }
    }//GEN-LAST:event_nacionalidadActionPerformed

    private void txtclave2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclave2KeyTyped
        txtclave2.setBackground(Color.white);
    }//GEN-LAST:event_txtclave2KeyTyped

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtnombres.setText(null);
        txtapellidos.setText(null);
        txtci.setText(null);
        txtclave1.setText(null);
        txtclave2.setText(null);
        txttelefono.setText(null);
        txtusuario.setText(null);
        nacionalidad.setSelectedIndex(0);
        nacimiento.setDate(null);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        int value = -1;
        
        String nombres = txtnombres.getText();
        String apellidos = txtapellidos.getText();
        String id = txtci.getText();
        Date fechaNacimiento;
        fechaNacimiento = fechaNacimiento();
        int codigo;
        
        String telefono = txttelefono.getText();
        String usuario = txtusuario.getText();
        clave1 = txtclave1.getText();
        clave2 = txtclave2.getText();
        
        List<String> campos = new ArrayList<>();
        campos.add(nombres);
        campos.add(apellidos);
        campos.add(id);
        campos.add(telefono);
        campos.add(usuario);
        campos.add(clave1);
        campos.add(clave2);
        
        List<Integer> camposVacios = validar.camposVacios(campos);
        if (!camposVacios.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos obligatorios vacios"); //mensaje

            for (Integer camposVacio : camposVacios) {  //devuelve la psocion de la lista de campos vacios leyendo la lista

                switch (camposVacio) {
                    case 0:
                        txtnombres.setBackground(Color.red);
                        break;
                    case 1:
                        txtapellidos.setBackground(Color.red);
                        break;
                    case 2:
                        txtci.setBackground(Color.red);
                        break;
                    case 3:
                        txttelefono.setBackground(Color.red);
                        break;
                    case 4:
                        txtusuario.setBackground(Color.red);
                        break;
                    case 5:
                        txtclave1.setBackground(Color.red);
                        break;
                    case 6:
                        txtclave2.setBackground(Color.red);
                        lblconfirmacion.setForeground(Color.red);
                        lblconfirmacion.setText("Contraseña incorrecta");
                        break;
                    
                }
            }
        } else if ((validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)).equals(validar.encriptaEnMD5(validar.encriptaEnMD5(clave2)))) && fechaNacimiento != null && ciudadania != null) {
            lblconfirmacion.setForeground(Color.green);
            lblconfirmacion.setText("Contraseña correcta");
            
            cliente = new Cliente(usuario, validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)), nombres, apellidos, ciudadania, id, fechaNacimiento, telefono);
            conexion.obtener();
            if (new Tabla(conexion).agregarValores(cliente) == -1) {
                btnlimpiarActionPerformed(evt);
                
            } else {
                conexion.cerrar();
                new Ingreso().setVisible(true);
                dispose();
                
            }
            
        } else if (!(validar.encriptaEnMD5(validar.encriptaEnMD5(clave1)).equals(validar.encriptaEnMD5(validar.encriptaEnMD5(clave2))))) {
            lblconfirmacion.setForeground(Color.red);
            lblconfirmacion.setText("Contraseña incorrecta");
            
        } else if (fechaNacimiento == null) {
            JOptionPane.showMessageDialog(null, "Fecha de nacimiento incorecta");
            
        } else if (ciudadania == null) {
            JOptionPane.showMessageDialog(null, "Nacionalidad incorrecta");
        }
        

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        new Bienvenida().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtclave1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclave1KeyTyped
        txtclave1.setBackground(Color.white);
        String clave = txtclave1.getText();
        jProgressBar1.setValue(validar.validarClave(clave));
        jProgressBar1.revalidate();
    }//GEN-LAST:event_txtclave1KeyTyped

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        txtusuario.setBackground(Color.white);
        char c;
        letrasNumeros(c = evt.getKeyChar(), evt, 3);
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        txttelefono.setBackground(Color.white);
        char c;
        letrasNumeros(c = evt.getKeyChar(), evt, 2);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciKeyTyped
        txtci.setBackground(Color.white);
    }//GEN-LAST:event_txtciKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        txtapellidos.setBackground(Color.white);
        char c;
        letrasNumeros(c = evt.getKeyChar(), evt, 1);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        txtnombres.setBackground(Color.white);
        char c;
        letrasNumeros(c = evt.getKeyChar(), evt, 1);
    }//GEN-LAST:event_txtnombresKeyTyped
    
    private void letrasNumeros(char c, java.awt.event.KeyEvent evt, int tipo) {
        switch (tipo) {
            case 1:
                if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != 32)) {
                    evt.consume();
                }
                break;
            
            case 2:
                if ((c < '0' || c > '9') && (c < 'A' || c > 'Z')) {
                    evt.consume();
                }
                break;
            
            case 3:
                if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9')) {
                    evt.consume();
                }
                break;
            
        }
        
    }
    
    private Date fechaNacimiento() {
        Date fechaNacimiento;
        date = new Date();
        
        try {
            if (nacimiento.getDate().after(date)) {
                
                JOptionPane.showMessageDialog(null, "Fecha de nacimiento incorrecta");
                fechaNacimiento = null;
            }
            fechaNacimiento = nacimiento.getDate();
        } catch (Exception ex) {
            fechaNacimiento = null;
        }
        return fechaNacimiento;
    }
    
    private DefaultComboBoxModel nacionalidad() {
        DefaultComboBoxModel paises = new DefaultComboBoxModel();
        paises.addElement("SELECCIONE UN PAIS");
        paises.addElement("AALAND ISLANDS");
        paises.addElement("AFGHANISTAN");
        paises.addElement("ALBANIA");
        paises.addElement("ALGERIA");
        paises.addElement("AMERICAN SAMOA");
        paises.addElement("ANDORRA");
        paises.addElement("ANGOLA");
        paises.addElement("ANGUILLA");
        paises.addElement("ANTARCTICA");
        paises.addElement("ANTIGUA AND BARBUDA");
        paises.addElement("ARGENTINA");
        paises.addElement("ARMENIA");
        paises.addElement("ARUBA");
        paises.addElement("AUSTRALIA");
        paises.addElement("AUSTRIA");
        paises.addElement("AZERBAIJAN");
        paises.addElement("BAHAMAS");
        paises.addElement("BAHRAIN");
        paises.addElement("BANGLADESH");
        paises.addElement("BARBADOS");
        paises.addElement("BELARUS");
        paises.addElement("BELGIUM");
        paises.addElement("BELIZE");
        paises.addElement("BENIN");
        paises.addElement("BERMUDA");
        paises.addElement("BHUTA");
        paises.addElement("BOLIVIA");
        paises.addElement("BOSNIA AND HERZEGOWINA");
        paises.addElement("BOTSWANA");
        paises.addElement("BOUVET ISLAND");
        paises.addElement("BRAZIL");
        paises.addElement("BRITISH INDIAN OCEAN TERRITORY");
        paises.addElement("BRUNEI DARUSSALAM");
        paises.addElement("BULGARIA");
        paises.addElement("BURKINA FASO");
        paises.addElement("BURUNDI");
        paises.addElement("CAMBODIA");
        paises.addElement("CAMEROON");
        paises.addElement("CANADA");
        paises.addElement("CAPE VERDE");
        paises.addElement("CAYMAN ISLANDS");
        paises.addElement("CENTRAL AFRICAN REPUBLIC");
        paises.addElement("CHAD");
        paises.addElement("CHILE");
        paises.addElement("CHINA");
        paises.addElement("CHRISTMAS ISLAND");
        paises.addElement("COCOS ISLANDS");
        paises.addElement("COLOMBIA");
        paises.addElement("COMOROS");
        paises.addElement("CONGO");
        paises.addElement("COOK ISLANDS");
        paises.addElement("COSTA RICA");
        paises.addElement("COTE D'IVOIRE");
        paises.addElement("CROATIA");
        paises.addElement("CUBA");
        paises.addElement("CYPRUS");
        paises.addElement("CZECH REPUBLIC");
        paises.addElement("DENMARK");
        paises.addElement("DJIBOUTI");
        paises.addElement("DOMINICA");
        paises.addElement("DOMINICAN REPUBLIC");
        paises.addElement("ECUADOR");
        paises.addElement("EGYPT");
        paises.addElement("EL SALVADOR");
        paises.addElement("EQUATORIAL GUINEA");
        paises.addElement("ERITREA");
        paises.addElement("ESTONIA");
        paises.addElement("ETHIOPIA");
        paises.addElement("FALKLAND ISLANDS (MALVINAS)");
        paises.addElement("FAROE ISLANDS");
        paises.addElement("FIJI");
        paises.addElement("FINLAND");
        paises.addElement("FRANCE");
        paises.addElement("FRENCH GUIANA");
        paises.addElement("FRENCH POLYNESIA");
        paises.addElement("FRENCH SOUTHERN TERRITORIES");
        paises.addElement("GABON");
        paises.addElement("GAMBIA");
        paises.addElement("GEORGIA");
        paises.addElement("GERMANY");
        paises.addElement("GHANA");
        paises.addElement("GIBRALTAR");
        paises.addElement("GREECE");
        paises.addElement("GREENLA");
        paises.addElement("GUADELOUPE");
        paises.addElement("GUAM");
        paises.addElement("GUATEMALA");
        paises.addElement("GUINEA");
        paises.addElement("GUINEA-BISSAU");
        paises.addElement("GUYANA");
        paises.addElement("HAITI");
        paises.addElement("HEARD AND MC DONALD ISLANDS");
        paises.addElement("HONDURAS");
        paises.addElement("HONG KONG");
        paises.addElement("HUNGARY");
        paises.addElement("ICELAND");
        paises.addElement("INDIA");
        paises.addElement("INDONESIA");
        paises.addElement("IRAN");
        paises.addElement("IRAQ");
        paises.addElement("IRELAND");
        paises.addElement("ISRAEL");
        paises.addElement("ITALY");
        paises.addElement("JAMAICA");
        paises.addElement("JAPAN");
        paises.addElement("JORDAN");
        paises.addElement("KAZAKHSTAN");
        paises.addElement("KENYA");
        paises.addElement("KIRIBATI");
        paises.addElement("KOREA NH");
        paises.addElement("KOREA SH");
        paises.addElement("KUWAIT");
        paises.addElement("KYRGYZSTAN");
        paises.addElement("LAO");
        paises.addElement("LATVIA");
        paises.addElement("LEBANON");
        paises.addElement("LESOTHO");
        paises.addElement("LIBERIA");
        paises.addElement("LIBYAN ARAB JAMAHIRIA");
        paises.addElement("LIECHTENSTEIN");
        paises.addElement("LITHUANIA");
        paises.addElement("LUXEMBOURG");
        paises.addElement("MACAU");
        paises.addElement("MACEDONIA");
        paises.addElement("MADAGASCAR");
        paises.addElement("MALAWI");
        paises.addElement("MALAYSIA");
        paises.addElement("MALDIVES");
        paises.addElement("MALI");
        paises.addElement("MALTA");
        paises.addElement("MARSHALL ISLANDS");
        paises.addElement("MARTINIQUE");
        paises.addElement("MAURITANIA");
        paises.addElement("MAURITIUS");
        paises.addElement("MAYOTTE");
        paises.addElement("MEXICO");
        paises.addElement("MICRONESIA");
        paises.addElement("MOLDOVA");
        paises.addElement("MONACO");
        paises.addElement("MONGOLIA");
        paises.addElement("MONTSERRAT");
        paises.addElement("MOROCCO");
        paises.addElement("MOZAMBIQUE");
        paises.addElement("MYANMAR");
        paises.addElement("NAMIBIA");
        paises.addElement("NAURU");
        paises.addElement("NEPAL");
        paises.addElement("NETHERLANDS");
        paises.addElement("NETHERLANDS ANTILLES");
        paises.addElement("NEW CALEDONIA");
        paises.addElement("NEW ZEALAND");
        paises.addElement("NICARAGUA");
        paises.addElement("NIGER");
        paises.addElement("NIGERIA");
        paises.addElement("NIUE");
        paises.addElement("NORFOLK ISLAND");
        paises.addElement("NORTHERN MARIANA ISLANDS");
        paises.addElement("NORWAY");
        paises.addElement("OMAN");
        paises.addElement("PAKISTAN");
        paises.addElement("PALAU");
        paises.addElement("PALESTINIAN TERRITORY");
        paises.addElement("PANAMA");
        paises.addElement("PAPUA NEW GUINEA");
        paises.addElement("PARAGUAY");
        paises.addElement("PERU");
        paises.addElement("PHILIPPINES");
        paises.addElement("PITCAIRN");
        paises.addElement("POLAND");
        paises.addElement("PORTUGAL");
        paises.addElement("PUERTO RICO");
        paises.addElement("QATAR");
        paises.addElement("REUNION");
        paises.addElement("ROMANIA");
        paises.addElement("RUSSIAN FEDERATION");
        paises.addElement("RWANDA");
        paises.addElement("SAINT HELENA");
        paises.addElement("SAINT KITTS AND NEVIS");
        paises.addElement("SAINT LUCIA");
        paises.addElement("SAINT PIERRE AND MIQUELON");
        paises.addElement("SAINT VINCENT AND THE GRENADINES");
        paises.addElement("SAMOA");
        paises.addElement("SAN MARINO");
        paises.addElement("SAO TOME AND PRINCIPE");
        paises.addElement("SAUDI ARABIA");
        paises.addElement("SENEGAL");
        paises.addElement("SERBIA AND MONTENEGRO");
        paises.addElement("SEYCHELLES");
        paises.addElement("SIERRA LEONE");
        paises.addElement("SINGAPORE");
        paises.addElement("SLOVAKIA");
        paises.addElement("SLOVENIA");
        paises.addElement("SOLOMON ISLANDS");
        paises.addElement("SOMALIA");
        paises.addElement("SOUTH AFRICA");
        paises.addElement("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANW");
        paises.addElement("SPAIN");
        paises.addElement("SRI LANKA");
        paises.addElement("SUDAN");
        paises.addElement("SURINAME");
        paises.addElement("SVALBARD AND JAN MAYEN ISLANDS");
        paises.addElement("SWAZILAND");
        paises.addElement("SWEDEN");
        paises.addElement("SWITZERLAND");
        paises.addElement("SYRIAN ARAB REPUBLIC");
        paises.addElement("TAIWAN");
        paises.addElement("TAJIKISTAN");
        paises.addElement("TANZANIA");
        paises.addElement("THAILAND");
        paises.addElement("TIMOR-LESTE");
        paises.addElement("TOGO");
        paises.addElement("TOKELAU");
        paises.addElement("TONGA");
        paises.addElement("TRINIDAD AND TOBAGO");
        paises.addElement("TUNISIA");
        paises.addElement("TURKEY");
        paises.addElement("TURKMENISTAN");
        paises.addElement("TURKS AND CAICOS ISLANDS");
        paises.addElement("TUVALU");
        paises.addElement("UGANDA");
        paises.addElement("UKRAINE");
        paises.addElement("UNITED ARAB EMIRATES");
        paises.addElement("UNITED KINGDOM");
        paises.addElement("UNITED STATES");
        paises.addElement("UNITED STATES MINOR OUTLYING ISLANDS");
        paises.addElement("URUGUAY");
        paises.addElement("UZBEKISTAN");
        paises.addElement("VANUATU");
        paises.addElement("VATICAN CITY STATE");
        paises.addElement("VENEZUELA");
        paises.addElement("VIET NAM");
        paises.addElement("VIRGIN ISLANDS BR");
        paises.addElement("VIRGIN ISLANDS US");
        paises.addElement("WALLIS AND FUTUNA ISLANDS");
        paises.addElement("WESTERN SAHARA");
        paises.addElement("YEMEN");
        paises.addElement("ZAMBIA");
        paises.addElement("ZIMBABWE");
        return paises;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblconfirmacion;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JComboBox<String> nacionalidad;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtci;
    private javax.swing.JPasswordField txtclave1;
    private javax.swing.JPasswordField txtclave2;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
