package modelo;

import javax.swing.DefaultComboBoxModel;

public class Paises {

    //        modelo.Cliente cliente = null; 
//                
//                Conexion conexion = new Conexion();
//                conexion.obtener();
//                new TablaCliente(conexion).agregarValores(new Cliente("cristianbb98", "12345", "Cristian", "Betancourt", "Ecuador", "1718057688", "09/03/1998","6039897"));
    DefaultComboBoxModel paises = new DefaultComboBoxModel();

    public Paises() {

        paises.addElement("AALAND ISLANDS");
        paises.addElement("AFGHANISTAN");
        paises.addElement("ALBANIA");
        paises.addElement("ALGERIA");
        paises.addElement("AMERICAN SAMOA");
        paises.addElement("ANDORRA");
        paises.addElement("ANGOLA");
        paises.addElement("ANGUILLA");
        paises.addElement("ANTARCTICA");
        paises.addElement("ANTIGUA AND BARBUDA");
        paises.addElement("ARGENTINA");
        paises.addElement("ARMENIA");
        paises.addElement("ARUBA");
        paises.addElement("AUSTRALIA");
        paises.addElement("AUSTRIA");
        paises.addElement("AZERBAIJAN");
        paises.addElement("BAHAMAS");
        paises.addElement("BAHRAIN");
        paises.addElement("BANGLADESH");
        paises.addElement("BARBADOS");
        paises.addElement("BELARUS");
        paises.addElement("BELGIUM");
        paises.addElement("BELIZE");
        paises.addElement("BENIN");
        paises.addElement("BERMUDA");
        paises.addElement("BHUTA");
        paises.addElement("BOLIVIA");
        paises.addElement("BOSNIA AND HERZEGOWINA");
        paises.addElement("BOTSWANA");
        paises.addElement("BOUVET ISLAND");
        paises.addElement("BRAZIL");
        paises.addElement("BRITISH INDIAN OCEAN TERRITORY");
        paises.addElement("BRUNEI DARUSSALAM");
        paises.addElement("BULGARIA");
        paises.addElement("BURKINA FASO");
        paises.addElement("BURUNDI");
        paises.addElement("CAMBODIA");
        paises.addElement("CAMEROON");
        paises.addElement("CANADA");
        paises.addElement("CAPE VERDE");
        paises.addElement("CAYMAN ISLANDS");
        paises.addElement("CENTRAL AFRICAN REPUBLIC");
        paises.addElement("CHAD");
        paises.addElement("CHILE");
        paises.addElement("CHINA");
        paises.addElement("CHRISTMAS ISLAND");
        paises.addElement("COCOS ISLANDS");
        paises.addElement("COLOMBIA");
        paises.addElement("COMOROS");
        paises.addElement("CONGO");
        paises.addElement("COOK ISLANDS");
        paises.addElement("COSTA RICA");
        paises.addElement("COTE D'IVOIRE");
        paises.addElement("CROATIA");
        paises.addElement("CUBA");
        paises.addElement("CYPRUS");
        paises.addElement("CZECH REPUBLIC");
        paises.addElement("DENMARK");
        paises.addElement("DJIBOUTI");
        paises.addElement("DOMINICA");
        paises.addElement("DOMINICAN REPUBLIC");
        paises.addElement("ECUADOR");
        paises.addElement("EGYPT");
        paises.addElement("EL SALVADOR");
        paises.addElement("EQUATORIAL GUINEA");
        paises.addElement("ERITREA");
        paises.addElement("ESTONIA");
        paises.addElement("ETHIOPIA");
        paises.addElement("FALKLAND ISLANDS (MALVINAS)");
        paises.addElement("FAROE ISLANDS");
        paises.addElement("FIJI");
        paises.addElement("FINLAND");
        paises.addElement("FRANCE");
        paises.addElement("FRENCH GUIANA");
        paises.addElement("FRENCH POLYNESIA");
        paises.addElement("FRENCH SOUTHERN TERRITORIES");
        paises.addElement("GABON");
        paises.addElement("GAMBIA");
        paises.addElement("GEORGIA");
        paises.addElement("GERMANY");
        paises.addElement("GHANA");
        paises.addElement("GIBRALTAR");
        paises.addElement("GREECE");
        paises.addElement("GREENLA");
        paises.addElement("GUADELOUPE");
        paises.addElement("GUAM");
        paises.addElement("GUATEMALA");
        paises.addElement("GUINEA");
        paises.addElement("GUINEA-BISSAU");
        paises.addElement("GUYANA");
        paises.addElement("HAITI");
        paises.addElement("HEARD AND MC DONALD ISLANDS");
        paises.addElement("HONDURAS");
        paises.addElement("HONG KONG");
        paises.addElement("HUNGARY");
        paises.addElement("ICELAND");
        paises.addElement("INDIA");
        paises.addElement("INDONESIA");
        paises.addElement("IRAN");
        paises.addElement("IRAQ");
        paises.addElement("IRELAND");
        paises.addElement("ISRAEL");
        paises.addElement("ITALY");
        paises.addElement("JAMAICA");
        paises.addElement("JAPAN");
        paises.addElement("JORDAN");
        paises.addElement("KAZAKHSTAN");
        paises.addElement("KENYA");
        paises.addElement("KIRIBATI");
        paises.addElement("KOREA NH");
        paises.addElement("KOREA SH");
        paises.addElement("KUWAIT");
        paises.addElement("KYRGYZSTAN");
        paises.addElement("LAO");
        paises.addElement("LATVIA");
        paises.addElement("LEBANON");
        paises.addElement("LESOTHO");
        paises.addElement("LIBERIA");
        paises.addElement("LIBYAN ARAB JAMAHIRIA");
        paises.addElement("LIECHTENSTEIN");
        paises.addElement("LITHUANIA");
        paises.addElement("LUXEMBOURG");
        paises.addElement("MACAU");
        paises.addElement("MACEDONIA");
        paises.addElement("MADAGASCAR");
        paises.addElement("MALAWI");
        paises.addElement("MALAYSIA");
        paises.addElement("MALDIVES");
        paises.addElement("MALI");
        paises.addElement("MALTA");
        paises.addElement("MARSHALL ISLANDS");
        paises.addElement("MARTINIQUE");
        paises.addElement("MAURITANIA");
        paises.addElement("MAURITIUS");
        paises.addElement("MAYOTTE");
        paises.addElement("MEXICO");
        paises.addElement("MICRONESIA");
        paises.addElement("MOLDOVA");
        paises.addElement("MONACO");
        paises.addElement("MONGOLIA");
        paises.addElement("MONTSERRAT");
        paises.addElement("MOROCCO");
        paises.addElement("MOZAMBIQUE");
        paises.addElement("MYANMAR");
        paises.addElement("NAMIBIA");
        paises.addElement("NAURU");
        paises.addElement("NEPAL");
        paises.addElement("NETHERLANDS");
        paises.addElement("NETHERLANDS ANTILLES");
        paises.addElement("NEW CALEDONIA");
        paises.addElement("NEW ZEALAND");
        paises.addElement("NICARAGUA");
        paises.addElement("NIGER");
        paises.addElement("NIGERIA");
        paises.addElement("NIUE");
        paises.addElement("NORFOLK ISLAND");
        paises.addElement("NORTHERN MARIANA ISLANDS");
        paises.addElement("NORWAY");
        paises.addElement("OMAN");
        paises.addElement("PAKISTAN");
        paises.addElement("PALAU");
        paises.addElement("PALESTINIAN TERRITORY");
        paises.addElement("PANAMA");
        paises.addElement("PAPUA NEW GUINEA");
        paises.addElement("PARAGUAY");
        paises.addElement("PERU");
        paises.addElement("PHILIPPINES");
        paises.addElement("PITCAIRN");
        paises.addElement("POLAND");
        paises.addElement("PORTUGAL");
        paises.addElement("PUERTO RICO");
        paises.addElement("QATAR");
        paises.addElement("REUNION");
        paises.addElement("ROMANIA");
        paises.addElement("RUSSIAN FEDERATION");
        paises.addElement("RWANDA");
        paises.addElement("SAINT HELENA");
        paises.addElement("SAINT KITTS AND NEVIS");
        paises.addElement("SAINT LUCIA");
        paises.addElement("SAINT PIERRE AND MIQUELON");
        paises.addElement("SAINT VINCENT AND THE GRENADINES");
        paises.addElement("SAMOA");
        paises.addElement("SAN MARINO");
        paises.addElement("SAO TOME AND PRINCIPE");
        paises.addElement("SAUDI ARABIA");
        paises.addElement("SENEGAL");
        paises.addElement("SERBIA AND MONTENEGRO");
        paises.addElement("SEYCHELLES");
        paises.addElement("SIERRA LEONE");
        paises.addElement("SINGAPORE");
        paises.addElement("SLOVAKIA");
        paises.addElement("SLOVENIA");
        paises.addElement("SOLOMON ISLANDS");
        paises.addElement("SOMALIA");
        paises.addElement("SOUTH AFRICA");
        paises.addElement("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANW");
        paises.addElement("SPAIN");
        paises.addElement("SRI LANKA");
        paises.addElement("SUDAN");
        paises.addElement("SURINAME");
        paises.addElement("SVALBARD AND JAN MAYEN ISLANDS");
        paises.addElement("SWAZILAND");
        paises.addElement("SWEDEN");
        paises.addElement("SWITZERLAND");
        paises.addElement("SYRIAN ARAB REPUBLIC");
        paises.addElement("TAIWAN");
        paises.addElement("TAJIKISTAN");
        paises.addElement("TANZANIA");
        paises.addElement("THAILAND");
        paises.addElement("TIMOR-LESTE");
        paises.addElement("TOGO");
        paises.addElement("TOKELAU");
        paises.addElement("TONGA");
        paises.addElement("TRINIDAD AND TOBAGO");
        paises.addElement("TUNISIA");
        paises.addElement("TURKEY");
        paises.addElement("TURKMENISTAN");
        paises.addElement("TURKS AND CAICOS ISLANDS");
        paises.addElement("TUVALU");
        paises.addElement("UGANDA");
        paises.addElement("UKRAINE");
        paises.addElement("UNITED ARAB EMIRATES");
        paises.addElement("UNITED KINGDOM");
        paises.addElement("UNITED STATES");
        paises.addElement("UNITED STATES MINOR OUTLYING ISLANDS");
        paises.addElement("URUGUAY");
        paises.addElement("UZBEKISTAN");
        paises.addElement("VANUATU");
        paises.addElement("VATICAN CITY STATE");
        paises.addElement("VENEZUELA");
        paises.addElement("VIET NAM");
        paises.addElement("VIRGIN ISLANDS BR");
        paises.addElement("VIRGIN ISLANDS US");
        paises.addElement("WALLIS AND FUTUNA ISLANDS");
        paises.addElement("WESTERN SAHARA");
        paises.addElement("YEMEN");
        paises.addElement("ZAMBIA");
        paises.addElement("ZIMBABWE");
    }

    public DefaultComboBoxModel getPaises() {
        return paises;
    }

}
